//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCabinet.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dental_dbEntities : DbContext
    {
        public dental_dbEntities()
            : base("name=dental_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<day> day { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<talon> talon { get; set; }
        public virtual DbSet<timetable> timetable { get; set; }
    }
}
