//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCabinet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class talon
    {
        public int tal_id { get; set; }
        public Nullable<int> pat_id { get; set; }
        public Nullable<int> ser_id { get; set; }
        public Nullable<System.DateTime> tal_date { get; set; }
        public Nullable<System.TimeSpan> tal_time { get; set; }
        public Nullable<int> doc_id { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual patient patient { get; set; }
        public virtual service service { get; set; }
    }
}
